### ISSUE TITLE
Actionsでデプロイできるようにする

### ISSUE THREAD

**Issue by miminashi** [GUND-ARM/favrial#1]
### ToDo

- [x] 先に #2 を済ませる
- [x] SSH鍵ペアを生成する
- [x] 公開鍵をサーバの `~/.ssh/authorized_keys`に追加する
- [ ] SSH認証情報をActionsに追加する
  - [x] SSH_USER
  - [x] SSH_HOSTNAME
  - [x] SSH_PRIVATE_KEY
  - [x] SSH_KNOWN_HOSTS
  - [x] SECRET_KEY_BASE
  - [x] TWITTER_CLIENT_ID
  - [x] TWITTER_CLIENT_SECRET
- [x] `.github/workflows/deploy.yml` を記述する
